"""
Clean all pipeline outputs for a fresh re-run.
Keeps: PDB files, raw data, scripts, CASBench raw download.
Deletes: Everything generated by the pipeline.

Usage:
    python scripts/diagnostics/clean_pipeline_outputs.py          # Dry run (show what would be deleted)
    python scripts/diagnostics/clean_pipeline_outputs.py --confirm # Actually delete
"""

import os
import sys
import shutil
from concurrent.futures import ThreadPoolExecutor

BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Directories to CLEAR (delete contents, keep the empty folder)
CLEAR_DIRS = [
    os.path.join(BASE_DIR, "data", "processed"),
    os.path.join(BASE_DIR, "features"),
    os.path.join(BASE_DIR, "models"),
    os.path.join(BASE_DIR, "results"),
    os.path.join(BASE_DIR, "data", "casbench", "features"),
    os.path.join(BASE_DIR, "data", "casbench", "labels"),
    os.path.join(BASE_DIR, "data", "casbench", "predictions"),
]

# Individual files to delete
DELETE_FILES = [
    os.path.join(BASE_DIR, "data", "casbench", "casbench_all_pdbs.csv"),
    os.path.join(BASE_DIR, "data", "casbench", "casbench_independent_pdbs.csv"),
    os.path.join(BASE_DIR, "data", "casbench", "casbench_homology.csv"),
]


def get_dir_stats(dir_path):
    """Get file count and total size for a directory."""
    if not os.path.exists(dir_path):
        return 0, 0
    total_size = 0
    count = 0
    for root, dirs, files in os.walk(dir_path):
        for f in files:
            fp = os.path.join(root, f)
            try:
                total_size += os.path.getsize(fp)
                count += 1
            except OSError:
                pass
    return count, total_size


def clear_directory(dir_path):
    """Delete all contents of a directory but keep the directory itself."""
    if not os.path.exists(dir_path):
        return 0
    count = 0
    for item in os.listdir(dir_path):
        item_path = os.path.join(dir_path, item)
        try:
            if os.path.isdir(item_path):
                shutil.rmtree(item_path)
            else:
                os.remove(item_path)
            count += 1
        except OSError as e:
            print(f"  WARNING: Could not delete {item_path}: {e}")
    return count


def main():
    confirm = '--confirm' in sys.argv

    print(f"Pipeline output cleaner")
    print(f"Base directory: {BASE_DIR}")
    print(f"Mode: {'DELETE' if confirm else 'DRY RUN (add --confirm to delete)'}")
    print()

    total_files = 0
    total_bytes = 0

    print("Directories to clear:")
    for d in CLEAR_DIRS:
        rel = os.path.relpath(d, BASE_DIR)
        count, size = get_dir_stats(d)
        total_files += count
        total_bytes += size
        status = "exists" if os.path.exists(d) else "missing"
        print(f"  {rel:<40} {count:>6} files  {size / 1024 / 1024:>10.1f} MB  [{status}]")

    print("\nIndividual files to delete:")
    for f in DELETE_FILES:
        rel = os.path.relpath(f, BASE_DIR)
        if os.path.exists(f):
            size = os.path.getsize(f)
            total_files += 1
            total_bytes += size
            print(f"  {rel:<40} {size / 1024:>10.1f} KB  [exists]")
        else:
            print(f"  {rel:<40} {'':>10}     [missing]")

    print(f"\nTotal: {total_files} files, {total_bytes / 1024 / 1024 / 1024:.2f} GB")

    if not confirm:
        print(f"\nDry run complete. Run with --confirm to delete.")
        return

    print(f"\nDeleting...")

    for d in CLEAR_DIRS:
        rel = os.path.relpath(d, BASE_DIR)
        if os.path.exists(d):
            deleted = clear_directory(d)
            print(f"  Cleared: {rel} ({deleted} items)")
            os.makedirs(d, exist_ok=True)
        else:
            os.makedirs(d, exist_ok=True)
            print(f"  Created: {rel}")

    for f in DELETE_FILES:
        rel = os.path.relpath(f, BASE_DIR)
        if os.path.exists(f):
            os.remove(f)
            print(f"  Deleted: {rel}")

    # Verify
    print(f"\nVerifying...")
    all_clean = True
    for d in CLEAR_DIRS:
        rel = os.path.relpath(d, BASE_DIR)
        remaining, _ = get_dir_stats(d)
        if remaining > 0:
            print(f"  WARNING: {rel} still has {remaining} files!")
            all_clean = False

    if all_clean:
        print(f"  All clean. Ready to re-run pipeline from step 2.")
    else:
        print(f"  Some files could not be deleted. Check warnings above.")


if __name__ == '__main__':
    main()
